services:
  nginx:
    image: nginx:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.4-fpm
    pull_policy: always
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
    depends_on:
      - composer
    command: ["sh", "-lc", "until [ -f vendor/autoload.php ]; do echo 'Waiting for composer install...'; sleep 0.5; done; php-fpm"]
    networks:
      - app-network

  composer:
    image: composer:latest
    pull_policy: always
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/app
    command: ["composer", "install", "--no-interaction", "--prefer-dist", "--no-ansi"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
